version: '3.8'

services:
  user-management:
    build:
      context: .
    container_name: user-management
    ports:
      - "8001:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    networks:
      - backend_network

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: charles
      POSTGRES_PASSWORD: usermanagementpass
      POSTGRES_DB: user_management_service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata:
