version: "3.8"

services:
  db:
    image: postgres:16
    container_name: generic_website_db
    environment:
      POSTGRES_USER: generic_user
      POSTGRES_PASSWORD: generic_db_password
      POSTGRES_DB: generic_website_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    container_name: generic_website_backend
    depends_on:
      - db
    ports:
      - "8443:443"
    volumes:
      - ./backend:/app
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    container_name: generic_website_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network: