version: "3.8"

services:
  web:
    container_name: generic-website-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
