"""Added confirmation token column

Revision ID: e23c05c336bd
Revises: 1914f1d8bf55
Create Date: 2024-05-20 21:12:36.572194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e23c05c336bd'
down_revision: Union[str, None] = '1914f1d8bf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'applications', ['application_id'])
    op.create_unique_constraint(None, 'teams', ['team_id'])
    op.add_column('users', sa.Column('confirmation_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'confirmation_token')
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'applications', type_='unique')
    # ### end Alembic commands ###
