import { IPageMenuItem } from '@/types/componentInterfaces';

export const systemMenuItems: IPageMenuItem[] = [
  {
    pageName: 'Home',
    href: '/',
    isHidden: false,
    pagePermission: ['0', '1', '2', '3', '4'],
    pageType: '3',
    description: '',
    type: 'item',
  },
  {
    pageName: 'Team Group',
    type: 'parent',
    isHidden: false,
    children: [
      {
        pageName: 'Teams',
        href: '/teams',
        isHidden: false,
        pagePermission: ['0', '1', '2', '3', '4'],
        pageType: '3',
        description: '',
        type: 'child',
      },
    ],
  },
  {
    pageName: 'News',
    href: '/news',
    isHidden: false,
    pagePermission: ['3', '1', '4', '2', '0', '5'],
    pageType: '1',
    description: '',
    type: 'item',
  },
  {
    pageName: 'Events',
    href: '/events',
    isHidden: false,
    pagePermission: ['3', '1', '4', '2', '0'],
    pageType: '0',
    description: '',
    type: 'item',
  },
  {
    pageName: 'Data',
    href: '/events',
    isHidden: false,
    pagePermission: ['3', '1', '4', '2', '0'],
    pageType: '0',
    description: '',
    type: 'item',
  },
  {
    pageName: 'Research',
    href: '/research',
    isHidden: false,
    pagePermission: ['3', '1', '4', '2', '0', '5'],
    pageType: '2',
    description: '',
    type: 'item',
  },
  {
    pageName: 'Teams',
    href: '/teams',
    isHidden: false,
    pagePermission: ['0', '1', '2', '3', '4'],
    pageType: '3',
    description: '',
    type: 'item',
  },
  {
    pageName: 'Admin Panel',
    href: '/admin-panel',
    isHidden: true,
    pagePermission: ['0', '1'],
    pageType: '3',
    type: 'item',
  },

  {
    pageName: 'Sign Up',
    href: '/sign-up',
    isHidden: true,
    pagePermission: ['0', '1', '2', '3', '4'],
    pageType: '3',
    type: 'item',
  },

  {
    pageName: 'Terms and Services',
    href: '/terms-and-services',
    isHidden: true,
    pagePermission: ['0', '1', '2'],
    pageType: '3',
    description: '',
    type: 'item',
  },
  {
    pageName: 'User Profile',
    href: '/user-profile',
    isHidden: true,
    pagePermission: ['0', '1', '2', '3', '4'],
    pageType: '3',
    type: 'item',
  },
  {
    pageName: 'Access Denied',
    href: '/access-denied',
    isHidden: true,
    pagePermission: ['0', '1', '2', '3', '4'],
    pageType: '3',
    type: 'item',
  },
];

export const routes = [
  ...systemMenuItems,
  {
    pageName: 'Reset Password',
    href: '/reset-password',
    isHidden: true,
    pagePermission: ['0', '1', '2', '3', '4'],
    pageType: '3',
    type: 'item',
  },
  {
    pageName: 'Confirm User',
    href: '/confirm-user/',
    isHidden: true,
    pagePermission: ['0', '1', '2', '3', '4'],
    pageType: '3',
    type: 'item',
  },
];
