"""Change UI_About from Text to JSON

Revision ID: 096d56d8945c
Revises: 911e13bf3248
Create Date: 2024-08-16 18:40:02.085202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096d56d8945c'
down_revision: Union[str, None] = '911e13bf3248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_UserInfo', 'UI_About')
    op.add_column('T_UserInfo', sa.Column('UI_About', sa.JSON, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_UserInfo', 'UI_About')
    op.add_column('T_UserInfo', sa.Column('UI_About', sa.Text, nullable=True))
    # ### end Alembic commands ###
