"""Add ON DELETE CASCADE to user-page content association

Revision ID: 21de4ac8c14f
Revises: 8f78cca58dfc
Create Date: 2024-10-28 03:38:58.597266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21de4ac8c14f'
down_revision: Union[str, None] = '8f78cca58dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('T_UsersPageContents_UI_ID_fkey', 'T_UsersPageContents', type_='foreignkey')
    op.drop_constraint('T_UsersPageContents_PC_ID_fkey', 'T_UsersPageContents', type_='foreignkey')
    op.create_foreign_key('fk_t_userspagecontents_pc_id', 'T_UsersPageContents', 'T_PageContent', ['PC_ID'], ['PC_ID'], ondelete='CASCADE')
    op.create_foreign_key( 'fk_t_userspagecontents_ui_id', 'T_UsersPageContents', 'T_UserInfo', ['UI_ID'], ['UI_ID'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_t_userspagecontents_pc_id', 'T_UsersPageContents', type_='foreignkey')
    op.drop_constraint( 'fk_t_userspagecontents_ui_id', 'T_UsersPageContents', type_='foreignkey')
    op.create_foreign_key('T_UsersPageContents_PC_ID_fkey', 'T_UsersPageContents', 'T_PageContent', ['PC_ID'], ['PC_ID'])
    op.create_foreign_key('T_UsersPageContents_UI_ID_fkey', 'T_UsersPageContents', 'T_UserInfo', ['UI_ID'], ['UI_ID'])
    # ### end Alembic commands ###
