"""Added PG_DisplayURL to page

Revision ID: 2f39e1221b5f
Revises: 41358d3a7207
Create Date: 2024-08-26 14:18:32.123281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f39e1221b5f'
down_revision: Union[str, None] = '41358d3a7207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('T_Page', sa.Column('PG_DisplayURL', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_Page', 'PG_DisplayURL')
    # ### end Alembic commands ###
