"""Change Page Display URL Size

Revision ID: 5434a46e7a8f
Revises: 22401bd0b1d7
Create Date: 2024-11-22 10:14:22.906524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5434a46e7a8f'
down_revision: Union[str, None] = '22401bd0b1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '22401bd0b1d7'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('T_Page', 'PG_DisplayURL',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    
    op.execute("ALTER TYPE e_memberposition ADD VALUE 'PRINCIPAL_INVESTIGATOR'")
    op.execute("ALTER TYPE e_memberposition ADD VALUE 'APPLICANT'")
    op.execute("ALTER TYPE e_memberposition ADD VALUE 'CO_APPLICANT'")
    op.execute("ALTER TYPE e_memberposition ADD VALUE 'RESEARCH_MANAGER'")
    op.execute("ALTER TYPE e_memberposition ADD VALUE 'RESEARCH_ASSISTANT'")
    op.execute("ALTER TYPE e_memberposition ADD VALUE 'RESEARCH_ASSOCIATE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('T_Page', 'PG_DisplayURL',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
