"""Change Page Display URL Size

Revision ID: 5434a46e7a8f
Revises: 
Create Date: 2024-11-22 10:14:22.906524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5434a46e7a8f'
down_revision: Union[str, None] = 'b766b82bdb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = 'b766b82bdb19'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('T_Page', 'PG_DisplayURL',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'PRINCIPAL_INVESTIGATOR' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'e_memberposition')) THEN
                ALTER TYPE e_memberposition ADD VALUE 'PRINCIPAL_INVESTIGATOR';
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'APPLICANT' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'e_memberposition')) THEN
                ALTER TYPE e_memberposition ADD VALUE 'APPLICANT';
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'CO_APPLICANT' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'e_memberposition')) THEN
                ALTER TYPE e_memberposition ADD VALUE 'CO_APPLICANT';
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'RESEARCH_MANAGER' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'e_memberposition')) THEN
                ALTER TYPE e_memberposition ADD VALUE 'RESEARCH_MANAGER';
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'RESEARCH_ASSISTANT' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'e_memberposition')) THEN
                ALTER TYPE e_memberposition ADD VALUE 'RESEARCH_ASSISTANT';
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'RESEARCH_ASSOCIATE' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'e_memberposition')) THEN
                ALTER TYPE e_memberposition ADD VALUE 'RESEARCH_ASSOCIATE';
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('T_Page', 'PG_DisplayURL',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
