"""drop confirmation token column from table

Revision ID: 5e121d26e44f
Revises: a2f8fd58fee4
Create Date: 2024-05-30 16:10:25.322267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e121d26e44f'
down_revision: Union[str, None] = 'a2f8fd58fee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_UserInfo', 'UI_ConfirmationTokenHash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
