"""Add UI_About column to T_UserInfo table

Revision ID: 74396326c89b
Revises: 71451ede85e2
Create Date: 2024-07-22 19:29:52.362451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74396326c89b'
down_revision: Union[str, None] = '71451ede85e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('T_UserInfo', sa.Column('UI_About', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_UserInfo', 'UI_About')
    # ### end Alembic commands ###
