"""Added email address column to table

Revision ID: 773f7d25f6e4
Revises: ca227a60f717
Create Date: 2024-05-28 13:41:06.796815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773f7d25f6e4'
down_revision: Union[str, None] = 'ca227a60f717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('T_UserInfo', sa.Column('UI_Email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'T_UserInfo', ['UI_Email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'T_UserInfo', type_='unique')
    op.drop_column('T_UserInfo', 'UI_Email')
    # ### end Alembic commands ###
