"""Added confirmation token column to user column

Revision ID: 816e8476abe7
Revises: 773f7d25f6e4
Create Date: 2024-05-28 14:08:10.250002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '816e8476abe7'
down_revision: Union[str, None] = '773f7d25f6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('T_UserInfo', sa.Column('UI_ConfirmationTokenHash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_UserInfo', 'UI_ConfirmationTokenHash')
    # ### end Alembic commands ###
