"""Added many-to-many relationship between users and page content

Revision ID: 8f78cca58dfc
Revises: 2f39e1221b5f
Create Date: 2024-10-27 20:28:30.721425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f78cca58dfc'
down_revision: Union[str, None] = '2f39e1221b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_UsersPageContents',
    sa.Column('UI_ID', sa.UUID(), nullable=False),
    sa.Column('PC_ID', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['PC_ID'], ['T_PageContent.PC_ID'], ),
    sa.ForeignKeyConstraint(['UI_ID'], ['T_UserInfo.UI_ID'], ),
    sa.PrimaryKeyConstraint('UI_ID', 'PC_ID')
    )
  
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_UsersPageContents')
    # ### end Alembic commands ###
