"""added member position to user column

Revision ID: 911e13bf3248
Revises: 9f2477c24cfe
Create Date: 2024-07-30 13:30:44.014628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911e13bf3248'
down_revision: Union[str, None] = '9f2477c24cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

enum_type = sa.Enum('DIRECTOR', 'POSTDOC', 'PHD', 'MASTER', 'UNDERGRAD', name='e_memberposition')


def upgrade() -> None:

    enum_type.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('T_UserInfo', sa.Column('UI_MemberPosition', enum_type, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_UserInfo', 'UI_MemberPosition')
    # ### end Alembic commands ###
