"""Updated the size of confirmation token

Revision ID: a2f8fd58fee4
Revises: 816e8476abe7
Create Date: 2024-05-28 15:11:35.505494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f8fd58fee4'
down_revision: Union[str, None] = '816e8476abe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('T_UserInfo', 'UI_ConfirmationTokenHash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('T_UserInfo', 'UI_ConfirmationTokenHash',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
