"""Added unique constraint to PG_Name in T_Page

Revision ID: c31c840d0c1d
Revises: 5e121d26e44f
Create Date: 2024-05-30 17:26:28.597728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31c840d0c1d'
down_revision: Union[str, None] = '5e121d26e44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'T_Page', ['PG_Name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'T_Page', type_='unique')
    # ### end Alembic commands ###
