"""Initial migration

Revision ID: ca227a60f717
Revises: 
Create Date: 2024-05-27 22:20:01.791737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca227a60f717'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_Page',
    sa.Column('PG_ID', sa.UUID(), nullable=False),
    sa.Column('PG_Type', sa.Enum('SinglePage', 'PageList', 'ResList', name='e_pagetype'), nullable=False),
    sa.Column('PG_Name', sa.String(length=100), nullable=False),
    sa.Column('PG_Permission', sa.ARRAY(sa.Enum('SuperAdmin', 'Admin', 'Member', 'User', 'Public', name='e_userrole')), nullable=False),
    sa.Column('PG_Other', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PG_ID')
    )
    op.create_table('T_UserInfo',
    sa.Column('UI_ID', sa.UUID(), nullable=False),
    sa.Column('UI_FirstName', sa.String(length=50), nullable=False),
    sa.Column('UI_LastName', sa.String(length=50), nullable=False),
    sa.Column('UI_PasswordHash', sa.String(length=255), nullable=False),
    sa.Column('UI_Role', sa.Enum('SuperAdmin', 'Admin', 'Member', 'User', 'Public', name='e_userrole'), nullable=False),
    sa.Column('UI_Status', sa.Enum('Active', 'Unauthenticated', 'Disabled', name='e_status'), nullable=False),
    sa.Column('UI_City', sa.String(length=100), nullable=True),
    sa.Column('UI_Province', sa.String(length=100), nullable=True),
    sa.Column('UI_Country', sa.String(length=100), nullable=True),
    sa.Column('UI_PostalCode', sa.String(length=20), nullable=True),
    sa.Column('UI_PhotoURL', sa.String(length=255), nullable=True),
    sa.Column('UI_PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('UI_Organization', sa.String(length=100), nullable=True),
    sa.Column('UI_RegDate', sa.DateTime(), nullable=True),
    sa.Column('UI_Other', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('UI_ID')
    )
    op.create_table('T_PageContent',
    sa.Column('PC_ID', sa.UUID(), nullable=False),
    sa.Column('UI_ID', sa.UUID(), nullable=False),
    sa.Column('PG_ID', sa.UUID(), nullable=False),
    sa.Column('PC_Title', sa.String(length=200), nullable=False),
    sa.Column('PC_ThumbImgURL', sa.String(length=255), nullable=True),
    sa.Column('PC_Content', sa.JSON(), nullable=False),
    sa.Column('PC_CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('PC_LastUpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('PC_DisplayURL', sa.String(length=255), nullable=True),
    sa.Column('PC_IsHidden', sa.Boolean(), nullable=True),
    sa.Column('PC_Other', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['PG_ID'], ['T_Page.PG_ID'], ),
    sa.ForeignKeyConstraint(['UI_ID'], ['T_UserInfo.UI_ID'], ),
    sa.PrimaryKeyConstraint('PC_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_PageContent')
    op.drop_table('T_UserInfo')
    op.drop_table('T_Page')
    # ### end Alembic commands ###
