"""Add prefix, suffix, and unique URL

Revision ID: de6e7bfeeebc
Revises: 5434a46e7a8f
Create Date: 2024-11-25 09:07:29.120606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6e7bfeeebc'
down_revision: Union[str, None] = '5434a46e7a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('T_Page', 'PG_DisplayURL',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('T_UserInfo', sa.Column('UI_PREFIX', sa.String(length=10), nullable=True))
    op.add_column('T_UserInfo', sa.Column('UI_SUFFIX', sa.String(length=10), nullable=True))
    op.add_column('T_UserInfo', sa.Column('UI_UNIQUEURL', sa.String(length=150), nullable=False))
    op.create_index(op.f('ix_T_UserInfo_UI_UNIQUEURL'), 'T_UserInfo', ['UI_UNIQUEURL'], unique=True)
    op.create_index('ix_user_uniqueurl', 'T_UserInfo', ['UI_UNIQUEURL'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_uniqueurl', table_name='T_UserInfo')
    op.drop_index(op.f('ix_T_UserInfo_UI_UNIQUEURL'), table_name='T_UserInfo')
    op.drop_column('T_UserInfo', 'UI_UNIQUEURL')
    op.drop_column('T_UserInfo', 'UI_SUFFIX')
    op.drop_column('T_UserInfo', 'UI_PREFIX')
    op.alter_column('T_Page', 'PG_DisplayURL',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
