"""added blacklisted token table to db.

Revision ID: e5ef98f16229
Revises: 7b7456e2ac5b
Create Date: 2024-06-05 20:07:45.159959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ef98f16229'
down_revision: Union[str, None] = '7b7456e2ac5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
