"""added blacklisted token table to db.

Revision ID: eff90ba76e62
Revises: e5ef98f16229
Create Date: 2024-06-05 20:09:28.504765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff90ba76e62'
down_revision: Union[str, None] = 'e5ef98f16229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
